server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: http://localhost:61442/
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
#            - AddRequestHeader=req-header-key,req-header-value
#            - AddResponseHeader=res-header-key,res-header-value
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Inner Logging Filter
                preLogger: true
                postLogger: true
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalogs/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Inner Logging Filter
                preLogger: true
                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true