server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/junyisong/Wokrkspace/Java/spring-cloud/configuration
          